// Auto-generated by scripts/export-abis.js — do not edit manually
// Run `pnpm --filter @sof/contracts build` to regenerate

import _InfoFiMarket from './InfoFiMarket.json' with { type: 'json' };

// Helper: extract abi array from Foundry JSON or return as-is
const e = (json) => json.abi || json;

export const InfoFiMarketABI = e(_InfoFiMarket);
